version: '2'
networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.driver.mtu: ${MTU}

services:
    postgres:
        container_name: "postgres"
        restart: "always"
        image: "${NEXUS_REPO}/onap/vnfsdk/refrepo/postgres:${POSTGRES_TAG}"
        mem_limit: "1g"
        memswap_limit: "1g"
        ports:
         - "5432:5432"
        volumes:
            - /data/refrepo/postgres:/var/lib/postgresql/data

    refrepo:
        container_name: "refrepo"
        restart: "always"
        image: "${NEXUS_REPO}/onap/vnfsdk/refrepo:${REFREPO_TAG}"
        ports:
            - "8702-8703:8702-8703"
            - "8000:8000"
        environment:
            POSTGRES_IP: postgres
            JPDA_ADDRESS: 8000
            JPDA_TRANSPORT: dt_socket
        volumes:
            - /data/refrepo/csars:/service/webapps/ROOT/WEB-INF/tomcat/webapps/ROOT/CSAR
        links:
            - postgres
